10 sprint. Complete
f-berezyuk/Filmorate pull request #1
Opened 2024-06-22 22:57 UTC by f-berezyuk

Сделал всё.

2024-06-23 07:11 UTC, mikita95 requested changes
Все сделано просто отлично :) Очень аккуратный код. Оставил лишь небольшие замечания

2024-06-23 07:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService = new UserService();
Поле можно сделать private final, а также заинжектить сервис с помощью спринга, а не создавать вручную :)

2024-06-23 07:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Класс можно сделать `@Service` - бин спринга, и инжектить его, аналогично и с другими сервисами и репозиториями

2024-06-23 17:41 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService = new UserService();
Инъекции только в следующем спринте - Переделаю в 11ом спринте)

2024-06-23 17:42 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Это на следующие спринты. Там - да, будем через аннотации их подключать

2024-06-24 16:22 UTC, mikita95 approved these changes
Все сделано отлично :) Можно мержить пул-реквест

2024-06-30 20:02 UTC, merged