Add friends likes
f-berezyuk/Filmorate pull request #2
Opened 2024-07-06 15:38 UTC by f-berezyuk

11 спринт.

2024-07-07 12:46 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-07-07 12:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Integer like(Long filmId, Long userId, Boolean add) throws IllegalArgumentException {
Здесь можно использовать примитивный boolean

2024-07-07 12:46 UTC, mikita95 commented on pom.xml
> +        </dependency>
Номера версий лучше выносить в свойства pom файла, так и и будет проще управлять

2024-07-07 12:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final IdGenerator generator;
Idgenerator - это скорее часть реализации хранилища, можно перенести туда

2024-07-07 12:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Map<Long, Set<Long>> likes;
Хранилище лайков лучше было бы тоже перенести из сервиса :)

2024-07-07 21:28 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Map<Long, Set<Long>> likes;
Я не хотел делать хранилище, так как сущность лайков пока слишком простая.
Но я сделал) Немного неаккуратных решений, но теперь лайки тоже "хранилище"

2024-07-07 21:28 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final IdGenerator generator;
немного намудрил, но сделал.

2024-07-07 21:28 UTC, f-berezyuk commented on pom.xml
> +        </dependency>
Интересно, вынес все)

2024-07-07 21:28 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Integer like(Long filmId, Long userId, Boolean add) throws IllegalArgumentException {
Согласен! Исправил

2024-07-07 21:29 UTC, f-berezyuk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Map<Long, Set<Long>> likes;
Дополнение к этому и к комментарию про генератор - при подключении БД и гибернейта - головная боль с идентификаторами уйдёт, так как будут использованы инструменты гибернейта (или какую ORM нам дадут на курсе)

2024-07-12 11:08 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-07-15 19:44 UTC, merged